apiVersion: agroproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/fdelavalle/helm-charts
    targetRevision: HEAD
    path: nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true